name: Node.js Package

on:
    release:
        types: [created]

jobs:
    init:
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v4
            - uses: actions/setup-node@v4
              with:
                  node-version: 16
            - run: npm i

    build:
        runs-on: ubuntu-latest
        needs: init
        steps:
            - uses: actions/checkout@v4
            - uses: actions/setup-node@v4
              with:
                  node-version: 16
            - run: npm ci
            - run: npm run build # Assuming "build" is a script in your package.json

    change-file:
        runs-on: ubuntu-latest
        needs: build
        steps:
            - uses: actions/checkout@v4
            - uses: actions/setup-node@v4
              with:
                  node-version: 16
            - run: npm run chfile

    publish-gpr:
        needs: change-file
        runs-on: ubuntu-latest
        permissions:
            packages: write
            contents: read
        steps:
            - uses: actions/checkout@v4
            - uses: actions/setup-node@v4
              with:
                  node-version: 16
                  registry-url: https://npm.pkg.github.com/
            - run: npm ci
            - run: npm publish
              env:
                  NODE_AUTH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
